<a href="https://colab.research.google.com/github/Grey-matter2020/Machine-Learning/blob/main/Notebook/Python/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Why Numpy

1. Python package to handle 1,2,3d arrays
2. Faster than list
3. Designed for scientific computation

In [ ]:
import numpy as np

In [ ]:
a = np.array([0,1,2,3,4])
print (a)
print(type(a))

b = np.arange(5)
print(b)
print(type(b))

[0 1 2 3 4]
<class 'numpy.ndarray'>
[0 1 2 3 4]
<class 'numpy.ndarray'>


## Numpy is faster than list

In [ ]:
lst1 = range(1000)
%timeit [i**2 for i in lst1]

271 µs ± 33.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
arry1 = np.arange(1000)
%timeit arry1**2

1.59 µs ± 111 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Creating Arrays

In [ ]:
# 1d array
a= np.array([0,1,2,3,4,5])
print(a)
print(a.ndim)
print(a.shape)
print(len(a))

[0 1 2 3 4 5]
1
(6,)
6


In [ ]:
# 2d array
a= np.array([[0,1,2,3,4,5],[6,7,8,9,0,1]])
print(a)
print(a.ndim)
print(a.shape)
print(len(a))

[[0 1 2 3 4 5]
 [6 7 8 9 0 1]]
2
(2, 6)
2


In [ ]:
# 3d array
a= np.array([[[0,1,2,3],[6,7,0,1]],[[0,4,9,3],[8,3,0,1]],[[5,1,7,3],[8,8,0,1]]])
print(a)
print(a.ndim)
print(a.shape)
print(len(a))

[[[0 1 2 3]
  [6 7 0 1]]

 [[0 4 9 3]
  [8 3 0 1]]

 [[5 1 7 3]
  [8 8 0 1]]]
3
(3, 2, 4)
3


## Methods for creating arrays

In [ ]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a = np.arange(0,10,2)             # start, stop and step
print(a)                          # stop is not included 

[0 2 4 6 8]


In [ ]:
a = np.arange(0.5,10.5,2)             # start, stop and step
print(a)                              # stop is not included 

[0.5 2.5 4.5 6.5 8.5]


In [ ]:
a = np.arange(0.5,10.5,2.5)             # start, stop and step
print(a)                              # stop is not included 

[0.5 3.  5.5 8. ]


In [ ]:
a = np.linspace(0,100,20)         # start, stop, no of points     
print(a)                          # stop is included
print(len(a))

[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]
20


In [ ]:
a = np.linspace(0,100,21)         # start, stop, no of points     
print(a)                  
print(len(a))

[  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100.]
21


In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
a= np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
print(np.diag(a))

[1 2 3 4]


In [ ]:
a = np.random.rand(4)             # create an array of shape 4 with random values from a uniform distribution [0,1]
print(a)

[0.91912046 0.08948372 0.33471117 0.58264615]


In [ ]:
a = np.random.randn(4)             # create an array of shape 4 with random values from a unit standard distribution [u = 0,s.d = 1]
print(a)

[ 0.13668917  0.95677636  0.24379039 -1.18880859]


## Indexing & Slicing - very similar to what we have seen for other data structures

In [ ]:
a = np.linspace(0,100,20)         # start, stop, no of points     
print(a)                          # stop is included
print(len(a))

[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]
20


In [ ]:
print(a[0])                                 # array is ordered
print(a[-1])
print(a[1])
print(a[1:5])
print(a[::2])
print(a[::-1])
print(a[-1::-1])

0.0
100.0
5.2631578947368425
[ 5.26315789 10.52631579 15.78947368 21.05263158]
[ 0.         10.52631579 21.05263158 31.57894737 42.10526316 52.63157895
 63.15789474 73.68421053 84.21052632 94.73684211]
[100.          94.73684211  89.47368421  84.21052632  78.94736842
  73.68421053  68.42105263  63.15789474  57.89473684  52.63157895
  47.36842105  42.10526316  36.84210526  31.57894737  26.31578947
  21.05263158  15.78947368  10.52631579   5.26315789   0.        ]
[100.          94.73684211  89.47368421  84.21052632  78.94736842
  73.68421053  68.42105263  63.15789474  57.89473684  52.63157895
  47.36842105  42.10526316  36.84210526  31.57894737  26.31578947
  21.05263158  15.78947368  10.52631579   5.26315789   0.        ]


In [ ]:
a = np.linspace(0,100,20)         # start, stop, no of points     
print(a)                          # stop is included
print(len(a))

[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]
20


In [ ]:
a[0] = 0.1                                      # array is mutable
a[-1] = 99
print(a)

[ 0.1         5.26315789 10.52631579 15.78947368 21.05263158 26.31578947
 31.57894737 36.84210526 42.10526316 47.36842105 52.63157895 57.89473684
 63.15789474 68.42105263 73.68421053 78.94736842 84.21052632 89.47368421
 94.73684211 99.        ]


In [ ]:
a = np.linspace(0,100,21)         # start, stop, no of points     
print(a)                  
print(len(a))

[  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100.]
21


In [ ]:
a[[1,6,10]]                                           # array filtering, doesnt work out for lists

array([ 5., 30., 50.])

In [ ]:
a[a>2]                                           # array filtering

array([  5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,  55.,
        60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [ ]:
a[a%2==0]  

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
a[[1,6,10]] = -200

In [ ]:
a

array([   0., -200.,   10.,   15.,   20.,   25., -200.,   35.,   40.,
         45., -200.,   55.,   60.,   65.,   70.,   75.,   80.,   85.,
         90.,   95.,  100.])

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = a[1:5]
b

array([1, 2, 3, 4])

In [ ]:
b[0] = b[0]+10
b[1] = b[1]+10
b[2] = b[2]+10
b[3] = b[3]+10

In [ ]:
b

array([11, 12, 13, 14])

In [ ]:
a                             # a got updated as b,a shared memory  # happens with list also

array([ 0, 11, 12, 13, 14,  5,  6,  7,  8,  9])

In [ ]:
c = a[1:5].copy()
c[0] = c[0]+10
c[1] = c[1]+10
c[2] = c[2]+10
c[3] = c[3]+10
c

array([21, 22, 23, 24])

In [ ]:
a                           # a is not changed

array([ 0, 11, 12, 13, 14,  5,  6,  7,  8,  9])

## Indexing & Masking

In [ ]:
a = np.random.randint(0, 20, 15)
a

array([13, 12,  0,  8, 16, 18, 18,  1, 19, 14, 11,  0, 16,  6,  9])

In [ ]:
mask = (a % 2 == 0)
mask

array([False,  True,  True,  True,  True,  True,  True, False, False,
        True, False,  True,  True,  True, False])

In [ ]:
extract_from_a = a[mask]
extract_from_a

array([12,  0,  8, 16, 18, 18, 14,  0, 16,  6])

In [ ]:
a[mask] = -1
a

array([13, -1, -1, -1, -1, -1, -1,  1, 19, -1, 11, -1, -1, -1,  9])

## Array Operations

In [ ]:
a =  np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
a+1

array([2, 3, 4, 5, 6])

In [ ]:
a**2

array([ 1,  4,  9, 16, 25])

In [ ]:
b = np.ones(5) + 1
b


array([2., 2., 2., 2., 2.])

In [ ]:
a-b

array([-1.,  0.,  1.,  2.,  3.])

In [ ]:
a*b

array([ 2.,  4.,  6.,  8., 10.])

In [ ]:
a = np.array([[1,2,3],[1,2,3]])
print(a)
print(a.shape)

[[1 2 3]
 [1 2 3]]
(2, 3)


In [ ]:
b = np.array([[1,2],[1,2],[1,2]])
print(b)
print(b.shape)

[[1 2]
 [1 2]
 [1 2]]
(3, 2)


In [ ]:
a*a

array([[1, 4, 9],
       [1, 4, 9]])

In [ ]:
a*b

ValueError: ignored

In [ ]:
a.dot(b)

array([[ 6, 12],
       [ 6, 12]])

In [ ]:
a = np.array([1, 2, 3, 4])             # element wise
b = np.array([5, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [ ]:
a = np.array([1, 2, 3, 4])             # element wise
b = np.array([5, 2, 2, 4])
a > b

array([False, False,  True, False])

In [ ]:
a = np.array([1, 2, 3, 4])             # array wise
b = np.array([5, 2, 2, 4])
np.array_equal(a,b)

False

## Basic Reductions

In [ ]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [ ]:
x = np.array([1, 2, 3, 4])
np.min(x)

1

In [ ]:
np.argmin(x)

0

In [ ]:
x = np.array([1, 2, 3, 4])
np.max(x)

4

In [ ]:
np.argmax(x)

3

In [ ]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [ ]:
x.sum(axis =0)                   # column wise

array([3, 3])

In [ ]:
x.sum(axis =1)                   # row wise   

array([2, 4])

In [ ]:
y = np.array([[1, 2, 3], [5, 6, 1]])
y.mean()

3.0

In [ ]:
y

array([[1, 2, 3],
       [5, 6, 1]])

In [ ]:
y = np.array([[1, 2, 3], [5, 6, 1]])          # index/row impacted or column wise
np.mean(y,axis=0)

array([3., 4., 2.])

In [ ]:
y = np.array([[1, 2, 3], [5, 6, 1]])          # column impacted or row wise
np.mean(y,axis=1)

array([2., 4.])

In [ ]:
y = np.array([[1, 2, 3], [5, 6, 1]])          # column impacted or row wise
np.mean(y,axis=-1)

array([2., 4.])

In [ ]:
a = np.zeros((50, 50))
np.any(a != 0)

False

In [ ]:
#Note: can be used for array comparisions
a = np.zeros((50, 50))
np.all(a == 0)

True

In [ ]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
print(a<=b)
print(b<=c)
print((a <= b) & (b <= c))
print(((a <= b) & (b <= c)).all())

[ True  True  True  True]
[ True  True  True  True]
[ True  True  True  True]
True


In [ ]:
import numpy as np
np.array([True,True,True]).all()

True

## Broadcasting

In [ ]:
import numpy as np
a = np.arange(0, 40, 10)
print(a)
print("*************")
b = np.tile(a,(3,1))
print(b)
print("*************")
c=b.T
print(c)

[ 0 10 20 30]
*************
[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
*************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [ ]:
d = np.array([0, 1, 2])
d

array([0, 1, 2])

In [ ]:
b+d

ValueError: ignored

In [ ]:
c+d

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
e = np.array([1,2,3,4])
print(e)
print(e.ndim)
print(e.shape)

[1 2 3 4]
1
(4,)


In [ ]:
e = np.array([[1,2,3,4]])
print(e)
print(e.ndim)
print(e.shape)

[[1 2 3 4]]
2
(1, 4)


In [ ]:
a

array([ 0, 10, 20, 30])

In [ ]:
a+e

array([[ 1, 12, 23, 34]])

In [ ]:
b

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [ ]:
f = np.array([[1],[2],[3]])
print(f)
print(f.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [ ]:
b+f

array([[ 1, 11, 21, 31],
       [ 2, 12, 22, 32],
       [ 3, 13, 23, 33]])

## Shape Manipulation

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape

(2, 3)

In [ ]:
print(a.ravel())          # array flattening

[1 2 3 4 5 6]


In [ ]:
print(a.T.ravel())        # row wise flattening

[1 4 2 5 3 6]


In [ ]:
a= np.arange(10)
print(a)
print(a.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [ ]:
print(a.reshape(1,10))

[[0 1 2 3 4 5 6 7 8 9]]


In [ ]:
print(a.reshape(10,1))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [ ]:
a = np.arange(4*3*2)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
a.reshape(4,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
a.reshape(4,3,1)

ValueError: ignored

In [ ]:
a= a.reshape(4,3,2)
a[0, 2, 1]

5

## Array Sorting

In [ ]:
#Sorting along an axis:
a = np.array([[5, 4, 6], [2, 3, 2]])
b = np.sort(a, axis=1)                    # row wise or column impacted
print(a)                         
print(b)

[[5 4 6]
 [2 3 2]]
[[4 5 6]
 [2 2 3]]


In [ ]:
#Sorting along an axis:
a = np.array([[5, 4, 6], [2, 3, 2]])
a.sort(axis=1)   
print(a)                         

[[4 5 6]
 [2 2 3]]


In [ ]:
#Sorting along an axis:
a = np.array([[5, 4, 6], [2, 3, 2]])
print(a)
a.sort(axis=0)                         # column wise or row impacted
print(a)                         

[[5 4 6]
 [2 3 2]]
[[2 3 2]
 [5 4 6]]


In [ ]:
a = np.array([4, 3, 1, 2])
j = np.argsort(a)                       # returns the index of the sorted array
j

array([2, 3, 1, 0])